name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install flake8
      - name: Install flake8
        run: pip install flake8

      # Step 4: Run flake8 linter
      - name: Run flake8
        run: flake8 .
